//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothingForHands.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialSupply = new HashSet<MaterialSupply>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public int typeMaterial { get; set; }
        public string image { get; set; }
        public decimal cost { get; set; }
        public int costForGoods { get; set; }
        public int minCost { get; set; }
        public int quantityInPack { get; set; }
        public int idUnit { get; set; }
    
        public virtual TypeMaterial TypeMaterial1 { get; set; }
        public virtual UnitType UnitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSupply> MaterialSupply { get; set; }
    }
}
