//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothingForHands.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vm_MaterialDetails
    {
        public string Tип_материала { get; set; }
        public string Название_материала { get; set; }
        public int Количество_на_складе { get; set; }
        public Nullable<int> Код_поставщиков { get; set; }
        public string Цена { get; set; }
        public string Описание { get; set; }
        public string Кол_материалов_на_начало_месяца { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
    }
}
